FrauctionProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('description.urls')),
    path('SellerForm', include('seller.urls')),
	path('CustomerForm/', include('CustomerForm.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
        settings.MEDIA_ROOT, }),
    ]

description/urls.py
from django.conf.urls import url
from django.urls import path
from .views import desc, ask_question, answer_question

app_name = 'description'

urlpatterns = [
    path('<int:id>/<str:title>', desc, name="desc"),
    path('ask/<int:id>', ask_question, name="ask"),
    path('answer/<int:item_id>/<int:id>', answer_question, name="ans"),
]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    #path('sort_by',views.sort_by_choice,name='sort_by')
]

home/models.py
from django.db import models

# Create your models here.
class SortBy(models.Model):

    class Meta:
        verbose_name_plural = 'Sort-by(s)'

    sort_by_choice = models.CharField(max_length=30)
    lastSort = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sort_by_choice

home/forms.py
from django import forms

attrs = {
    'class': 'form-control form-group' 
}

sort_by_choices = (
    ('Newest',"Newest"),
    ('Oldest', "Oldest"),
    ('Alphabetical',"Alphabetical"),
    ('Price (from lowest)',"Price (from lowest)"),
    ('Price (from highest)',"Price (from highest)"),
    ('End Date (from nearest)',"End Date (from nearest)"),
    ('End Date (from farthest)',"End Date (from farthest)")
)

class SortByForm(forms.Form):
    sort_by =  forms.ChoiceField(label='Sort by',widget=forms.Select(attrs=attrs),choices=sort_by_choices, initial="Newest")

home/views.py
from django.shortcuts import render, redirect
from .forms import SortByForm
from seller.models import SellerModel
from .models import SortBy
from CustomerForm.models import Customer
from django.urls import reverse
from . import robot

# Create your views here.
def home(request):
    if request.method == 'POST':
        form = SortByForm(request.POST)
        if form.is_valid():
            this_choice = request.POST.get('sort_by')
            create_object(this_choice)
            
            lastSortObject = SortBy.objects.last()
            get_objects = get_objects_sorted_by(this_choice)
           
            response = {
                'title' : 'Frauction',
                'form' : form,
                'seller' : get_objects_sorted_by(this_choice),
                'last' : lastSortObject,
                'sellorbuy' : 'Sell',
                'navlink' : reverse('seller_create')
            }
            return render(request,("home.html"),response)
    else:
        form = SortByForm()
        create_object('Newest')
        lastSortObject = SortBy.objects.last()

        robot.update_price_robot()

    response = {
        'title' : 'Frauction',
        'form' : form,
        'seller' : get_objects_sorted_by('Newest'),  
        'last' : lastSortObject,
        'sellorbuy' : 'Sell',
        'navlink' : reverse('seller_create'),
    }
    return render(request,("home.html"),response)

def create_object(curr_choice):
    sortbyobjects = SortBy(sort_by_choice=curr_choice)
    sortbyobjects.save()

def get_objects_sorted_by(choice):
    if(choice=='Newest'):
        return SellerModel.objects.all().order_by('-start_date')
    elif(choice=='Oldest'):
        return SellerModel.objects.all().order_by('start_date')
    elif(choice=='Alphabetical'):
        return SellerModel.objects.all().order_by('title')
    elif(choice=='Price (from lowest)'):
        return SellerModel.objects.all().order_by("price")
    elif(choice=='Price (from highest)'):
        return SellerModel.objects.all().order_by("-price")
    elif(choice=='End Date (from nearest)'):
        return SellerModel.objects.all().order_by("end_date")
    elif(choice=='End Date (from farthest)'):
        return SellerModel.objects.all().order_by('-end_date')

home/templates/home.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}

<div class="home">

    <div class="fixed-bg intro-background">
        <img src="{% static 'logo-horizontal.png' %}" class="gambar-logo" />
        <div class="subtitle">
            Best place to bid.
        </div>
    </div>

    <div class="fixed-bg">
        <div class="kasihjarak"></div>
        <div class="sort">
            <div class="flex-row">
                <form id="sortbutton" action="{% url 'home:home' %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_table }}
                    <button class="sort-button" type="submit" value="sort">Sort</button>
                </form>
            </div>
        </div>
        {% if seller.count %}
        <div class="flex-wrap">
            {% for item in seller %}
            <div class="card-barang">
                <img src="{{ item.image.url }}" width="230" height="180" class="gambar" />
                <h2><a href="{% url 'description:desc' id=item.id title=item.title %}">{{ item.title }}</a></h2>
                <h3>${{ item.price }}</h3>
                <div class="item-status">
                    {{item.status}}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="lastsort">
            <i>Last sorted by <b>{{last.sort_by_choice}}</b> order at <b>{{last.lastSort}}</b></i>
        </div>
        {% else %}
        <div class="belom-ada">
            Place your first items here!
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}