CustomerForm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'CustomerForm'

urlpatterns = [
	path('<int:id>', views.bid_form, name='bid'),
    path('thanks/<int:id>', views.place_bid, name='place_bid'),
	]

FrauctionProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('description.urls')),
    path('SellerForm', include('seller.urls')),
	path('CustomerForm/', include('CustomerForm.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
        settings.MEDIA_ROOT, }),
    ]

description/urls.py
from django.conf.urls import url
from django.urls import path
from .views import desc, ask_question, answer_question

app_name = 'description'

urlpatterns = [
    path('<int:id>/<str:title>', desc, name="desc"),
    path('ask/<int:id>', ask_question, name="ask"),
    path('answer/<int:item_id>/<int:id>', answer_question, name="ans"),
]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    #path('sort_by',views.sort_by_choice,name='sort_by')
]

description/models.py
from django.db import models
from seller.models import SellerModel

class Question(models.Model):
	item = models.ForeignKey(SellerModel, on_delete=models.CASCADE, related_name="questions")
	question = models.CharField(max_length=400, blank=False)
	time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.question

class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")
	answer = models.CharField(max_length=400, blank=False)
	time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.answer

description/forms.py
from django import forms

qn_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'message/question',
        }

ans_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'Write your reply',
        }

class QuestionForm(forms.Form):
    question = forms.CharField(label="", required=True, max_length=400, widget=forms.TextInput(attrs=qn_attrs))

class AnswerForm(forms.Form):
    answer = forms.CharField(label="", required=True, max_length=400, widget=forms.TextInput(attrs=ans_attrs))

description/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Question, Answer, SellerModel
from .forms import QuestionForm, AnswerForm
import datetime

def desc(request, id, title):

	item = SellerModel.objects.get(id=id)
	enddate = datetime.datetime(item.end_date.year, item.end_date.month, item.end_date.day, item.end_date.hour)
	daysleft = (enddate - datetime.datetime.now()).days
	hoursleft = (enddate - datetime.datetime.now()).seconds//3600
	countdown = str(daysleft) + " days "
	curorlast = "Current"
	onclick = ""

	if hoursleft == 1:
		countdown += str(hoursleft) + " hour"
	elif hoursleft > 1:
		countdown += str(hoursleft) + " hours"
	
	if daysleft < 0:
		countdown = "Time's Up"
		curorlast = "Final"
		onclick = "return false"

	lastbid = item.bids.last()
	lastprice = lastbid
	if lastbid == None:
		lastbid = 0
		lastprice = item.starting_price
	
	context = {
		'qnform': QuestionForm(),
		'ansform' : AnswerForm(),
        'title': "Frauction: " + item.title,
		'navlink' : reverse('seller_create'),
		'sellorbuy' : 'Sell',
		'item' : item,
		'countdown' : countdown,
		'oc' : onclick,
		'curorlast' : curorlast,
		'lastbid' : lastbid,
		'lastprice' : lastprice,
		'bidcount' : item.bids.count,
    }
	return render(request, 'description_page.html', context)

def ask_question(request, id):

	item = SellerModel.objects.get(id=id)
	if request.method == "POST":
		form = QuestionForm(request.POST)
		if form.is_valid():
			Question.objects.create(
				item = item,
				question = request.POST.get('question'),
				time = request.POST.get('time'),
			)

	return redirect('description:desc', id, item.title)

def answer_question(request, id, item_id):

	item = SellerModel.objects.get(id=item_id)
	if request.method == "POST":
		form = AnswerForm(request.POST)
		if form.is_valid():
			Answer.objects.create(
				question = Question.objects.get(id=id),
				answer = request.POST.get('answer'),
				time = request.POST.get('time'),
			)
	else:
		form = AnswerForm()
	return redirect('description:desc', item_id, item.title)

description/templates/description_page.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/description.css' %}">
{% endblock %}

{% block content %}

<h1 class="center start">{{ item.title }}</h1>
<div class="flex-pc item">
    <div class="itemdiv">
        <img src="{{ item.image.url }}" alt="" id="itemimg"/>
    </div>    
    <div class="itemdiv">
        <p class="center">This Auction Ends in:</p>
        <p class="center" id="specialtxt">{{ countdown }}</p>
        <p class="center">{{ curorlast }} Price: <span id="specialtxt">${{ lastprice }}</span></p>
        <a href="{% url 'CustomerForm:bid' id=item.id %}" class="btn btn-place-bid" id="placebid" onclick="{{ oc }}">Place Bid</a>
    </div>
</div>

<div id="infodiv"> 
    <h3>Information</h3>
    <div id="infodivborder">
    <div class="center flex-pc">
        <div class="infoheaderdiv infoactive" onclick=infoOn(id) id="auctxt">Auction Details</div>
        <div class="infoheaderdiv" onclick=infoOn(id) id="paytxt">Payment</div>
        <div class="infoheaderdiv" onclick=infoOn(id) id="itemdesctxt">Item Description</div>
        <div class="infoheaderdiv" onclick=infoOn(id) id="additxt">Additionals</div>
    </div>
    <div><p id="infocontent">
        Starting Bid: ${{ item.starting_price }}<br>
        Current Bid: ${{ lastbid }} <br>
        Start Date: {{ item.start_date }}<br>
        End Date: {{ item.end_date }}<br>
        Bid Count: {{ bidcount }}
        </p></div>
    </div>

    <div id="qnamar">
    <h3>QnA</h3>
    <form class="flex-pc" method="POST" action="{% url 'description:ask' id=item.id %}">
        {% csrf_token %}
        {{ qnform }}
    <button type="submit" class="btn btn-submit">Submit</button>
    </form>
    <div id="qna">
        {% if item.questions.all.count %}
        {% for q in item.questions.all %}
        <p class="qnaheader">Q: {{q}}</p>
        <p class="timetxt">{{q.time}}</p>
        <p class="replytxt" id="replytxt {{q.id}}" onclick=displayForm({{q.id}})>Reply</p>
        <div style="filter:opacity(0%)" class="ansform" id="ansform {{ q.id }}"> 
            <form class='flex' method='POST' action="{% url 'description:ans' id=q.id item_id=q.item_id %}">
                {% csrf_token %}
                {{ ansform }}
            <button type="submit" class='btn btn-submit'>Submit</button>
            </form>
        </div>

        {% for a in q.answers.all %}
        <p class="qnaheader">A: {{a}}</p>
        <p class="timetxt">{{a.time}}</p>
        {% endfor %}

        {% endfor %}

        {% else %}
        <p>Ask us anything!</p>
        {% endif %} 
    </div>
    </div>
</div>

<script>
    function infoOn(id) {
        document.getElementsByClassName("infoactive")[0].className = "infoheaderdiv";
        document.getElementById(id).className = "infoheaderdiv infoactive";
        var info = document.getElementById("infocontent");
        info.className = "infocontentblue";
        if (id == "auctxt") {
            info.innerHTML = "Starting Bid: ${{ item.starting_price }}<br>Current Bid: ${{ lastbid }}<br>Start Date: {{ item.start_date }}<br>End Date: {{ item.end_date }}<br>Bid Count: {{ bidcount }}";
            info.className = "";
        } else if (id == "paytxt") {
            info.innerHTML = "No data regarding payment methods.";
        } else if (id == "itemdesctxt") {
            info.innerHTML = "{{ item.description }}";
            info.className = "";
        } else if (id == "additxt") {
            info.innerHTML = "No additional data";
        }
    }

    function displayForm(id) {
        document.getElementById("ansform " +id).style = "filter:opacity(100%)";
        document.getElementById("replytxt "+id).innerHTML = "";
    }
</script>

{% endblock %}