CustomerForm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'CustomerForm'

urlpatterns = [
	path('<int:id>', views.bid_form, name='bid'),
    path('thanks/<int:id>', views.place_bid, name='place_bid'),
	]

FrauctionProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('description.urls')),
    path('SellerForm', include('seller.urls')),
	path('CustomerForm/', include('CustomerForm.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
        settings.MEDIA_ROOT, }),
    ]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    #path('sort_by',views.sort_by_choice,name='sort_by')
]

CustomerForm/models.py
from django.db import models
from seller.models import SellerModel

class Customer(models.Model):

	item = models.ForeignKey(SellerModel, on_delete=models.CASCADE, related_name="bids")
	name = models.CharField(max_length=100, blank=False)
	price = models.PositiveIntegerField(default=0)
	address =  models.CharField(max_length=10000, blank=False)
	email =  models.EmailField(max_length=254, blank=False)
	phone_number =  models.CharField(max_length=20, blank=False)
	terms_confirm =  models.BooleanField(blank=False)
	
	def __str__(self):
		return str(self.price)

CustomerForm/forms.py
from django import forms
from .models import Customer
from django.forms import ModelForm

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['name','price','address','email','phone_number','terms_confirm']
        labels = {'name':'Name','price':'Price','address':'Address','email':'E-mail','phone_number':'Phone Number','terms_confirm':'I have agreed to the terms and condition'}
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control','type':'text'}),
            'price':forms.NumberInput(attrs={'class':'form-control','type':'number'}),
            'address':forms.Textarea(attrs={'class':'form-control','type':'textarea','row':'10'}),
            'email':forms.EmailInput(attrs={'class':'form-control','type':'email'}),
            'phone_number':forms.TextInput(attrs={'class':'form-control','type':'text'}),
            'terms_confirm':forms.CheckboxInput(attrs={'class':'form-control','type':'checkbox'}),
            }

CustomerForm/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .forms import CustomerForm
from .models import Customer
from django.shortcuts import redirect
from .models import SellerModel

def bid_form(request, id):
	item = SellerModel.objects.get(id=id)
	context = {
		'item' : item,
		'form' : CustomerForm(),
		'title' : 'Place Bid',
		'navlink' : reverse('seller_create'),
		'sellorbuy' : 'Sell',
		}
			
	return render(request, 'BuyerForm.html', context)	

def place_bid(request, id):
	if request.method == "POST":
		form = CustomerForm(request.POST)
		if form.is_valid():
			tc = False
			if request.POST.get('terms_confirm') == 'on':
				tc = True
			
			Customer.objects.create(
				item = SellerModel.objects.get(id=id),
				name = request.POST.get('name'),
				price = request.POST.get('price'),
				address = request.POST.get('address'),
				email = request.POST.get('email'),
				phone_number = request.POST.get('phone_number'),
				terms_confirm = tc,)
			
			lastCustomer = Customer.objects.last()
			context = {
				'title' : 'Place Bid',
				'last' : lastCustomer,
				'navlink' : reverse('seller_create'),
				'sellorbuy' : 'Sell',
			}
			return render(request,'thanks_bid.html', context)	
			
		
		
		
		
		
		
		

CustomerForm/templates/BuyerForm.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
	crossorigin="anonymous"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/buyer.css' %}">
{% endblock %}

{% block content %}
<div class="containerr">
    <h1 align="center"style="font-family:livvic">Please Fill Out This Information</h1>
  <div class="container"style="font-family:livvic">
    <form action="{% url 'CustomerForm:place_bid' id=item.id %}" method="post">
      {% csrf_token %} {% for fields in form %}
      <div class="form-group row">
        <label class="col-sm-2 col-form-label mr-2"> {{ fields.label_tag }}</label>
        <div class="col-sm-6">
          {{ fields }}
        </div>
      </div>
      {% endfor %}
      <div class="form-group row">
        <div class="offset-xs-3 col-xs-9">
          <button class="btn btn-place-bid">Place Bid</button></a>
		</div>
      </div>
    </form>
  </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  
    {% endblock %}

CustomerForm/templates/thanks_bid.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% block css %}
<link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
/>
<link rel="stylesheet" type="text/css" href="{% static 'css/buyer.css' %}">
{% endblock %}

{% block content %}
<div class= "containerr">
	<h1 class="tulisan" >Thank You {{ last.name }} For Bidding with Frauction</h1>
    <p class="tulisan">We will contact you soon when the auction end</p>
    <a href= "{% url 'home:home' %}"><button type="button" class="btn btn-place-bid">Back to Home</button></a>

</div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
{% endblock %}